// Dummy data for testing purposes and seeing how the UI looks

export const games = [
  {
    id: 1,
    name: "Half-Life 2",
    image: "/pictures/hl2.png",
    achievements: {
      completed: 20,
      total: 33,
    },
    lastPlayed: new Date('2023-05-03'),
    achievementsList: [
      {
        id: 1,
        name: "City Escape",
        description: "Successfully escape the city",
        locked: false,
        unlockDate: new Date('2023-05-02'),
        hidden: false,
        image: "/pictures/achievement_images/hl2-city-escape.png",
        unlockPercentage: 34,
      },
      {
        id: 2,
        name: "Trusty Hardware",
        description: "Find the crowbar",
        locked: false,
        unlockDate: new Date('2023-05-03'),
        hidden: false,
        image: "/pictures/achievement_images/hl2-trusty-hardware.png",
        unlockPercentage: 70,
      },
      {
        id: 3,
        name: "Citizen Freeman",
        description: "Join the resistance",
        locked: true,
        unlockDate: null,
        hidden: false,
        image: "/pictures/achievement_images/hl2-citizen-freeman.png",
        unlockPercentage: 60,
      },
    ],
  },
  {
    id: 2,
    name: "Portal",
    image: "/pictures/portal.png",
    achievements: {
      completed: 10,
      total: 15,
    },
    lastPlayed: new Date('2023-05-11'),
    achievementsList: [
      {
        id: 1,
        name: "Welcome to Aperture",
        description: "Enter the Aperture Science Enrichment Center",
        locked: false,
        unlockDate: new Date('2023-05-10'),
        hidden: false,
        image: "/pictures/achievement_images/portal-welcome-to-aperture.png",
        unlockPercentage: 90,
      },
      {
        id: 2,
        name: "Portal Master",
        description: "Master the use of portals",
        locked: false,
        unlockDate: new Date('2023-05-11'),
        hidden: true,
        image: "/pictures/achievement_images/portal-portal-master.png",
        unlockPercentage: 37,
      },
      {
        id: 3,
        name: "Cake Is a Lie",
        description: "Discover the truth about the cake",
        locked: true,
        unlockDate: new Date('2023-05-11'),
        hidden: false,
        image: "/pictures/achievement_images/portal-cake-is-a-lie.png",
        unlockPercentage: 24,
      },
    ],
  },
  {
    id: 3,
    name: "Team Fortress 2",
    image: "/pictures/tf2.png",
    achievements: {
      completed: 100,
      total: 520,
    },
    lastPlayed: new Date('2023-05-05'),
    achievementsList: [
      {
        id: 1,
        name: "Capture the Flag",
        description: "Capture the enemy flag",
        locked: false,
        unlockDate: new Date('2023-04-25'),
        hidden: false,
        image: "/pictures/achievement_images/tf2-capture-the-flag.png",
        unlockPercentage: 83,
      },
      {
        id: 2,
        name: "King of the Hill",
        description: "Dominate the control point",
        locked: true,
        unlockDate: null,
        hidden: true,
        image: "/pictures/achievement_images/tf2-king-of-the-hill.png",
        unlockPercentage: 51,
      },
      {
        id: 3,
        name: "Payload",
        description: "Successfully push the payload",
        locked: false,
        unlockDate: new Date('2023-05-06'),
        hidden: false,
        image: "/pictures/achievement_images/tf2-payload.png",
        unlockPercentage: 95,
      },
    ],
  },
  {
    id: 4,
    name: "DOTA 2",
    image: "/pictures/dota2.png",
    achievements: {
      completed: 5,
      total: 167,
    },
    lastPlayed: new Date('2023-04-30'),
    achievementsList: [
      {
        id: 1,
        name: "First Blood",
        description: "Get the first kill in a match",
        locked: false,
        unlockDate: new Date('2023-04-01'),
        hidden: false,
        image: "/pictures/achievement_images/dota2-first-blood.png",
        unlockPercentage: 74,
      },
      {
        id: 2,
        name: "The International Champion",
        description: "Win The International tournament",
        locked: true,
        unlockDate: null,
        hidden: false,
        image: "/pictures/achievement_images/dota2-the-international-champion.png",
        unlockPercentage: 2,
      },
      {
        id: 3,
        name: "Tower Destroyer",
        description: "Destroy enemy towers",
        locked: false,
        unlockDate: new Date('2023-04-13'),
        hidden: true,
        image: "/pictures/achievement_images/dota2-tower-destroyer.png",
        unlockPercentage: 75,
      },
    ],
  },
  {
    id: 5,
    name: "Counter-Strike: Global Offensive",
    image: "/pictures/csgo.png",
    achievements: {
      completed: 150,
      total: 167,
    },
    lastPlayed: new Date('2023-04-02'),
    achievementsList: [
      {
        id: 1,
        name: "Bomb Defuser",
        description: "Successfully defuse the bomb",
        locked: false,
        unlockDate: new Date('2023-03-03'),
        hidden: false,
        image: "/pictures/achievement_images/csgo-bomb-defuser.png",
        unlockPercentage: 92,
      },
      {
        id: 2,
        name: "Headshot Master",
        description: "Get a headshot kill",
        locked: false,
        unlockDate: new Date('2023-03-15'),
        hidden: true,
        image: "/pictures/achievement_images/csgo-headshot-master.png",
        unlockPercentage: 89,
      },
      {
        id: 3,
        name: "Ninja Defuser",
        description: "Successfully defuse the bomb without being detected",
        locked: false,
        unlockDate: new Date('2023-04-02'),
        hidden: false,
        image: "/pictures/achievement_images/csgo-ninja-defuser.png",
        unlockPercentage: 12,
      },
      {
        id: 4,
        name: "Ace",
        description: "Eliminate the entire enemy team in a single round",
        locked: false,
        unlockDate: new Date('2023-04-10'),
        hidden: false,
        image: "/pictures/achievement_images/csgo-ace.png",
        unlockPercentage: 33,
      },
      {
        id: 5,
        name: "Master Strategist",
        description: "Win a round by executing a well-coordinated strategy",
        locked: true,
        unlockDate: null,
        hidden: false,
        image: "/pictures/achievement_images/csgo-master-strategist.png",
        unlockPercentage: 77,
      },
      {
        id: 6,
        name: "Legendary Sniper",
        description: "Get 100 sniper rifle kills",
        locked: false,
        unlockDate: new Date('2023-04-20'),
        hidden: true,
        image: "/pictures/achievement_images/csgo-legendary-sniper.png",
        unlockPercentage: 64,
      },
    ],
  },
  {
    id: 6,
    name: "The Elder Scrolls V: Skyrim",
    image: "/pictures/skyrim.png",
    achievements: {
      completed: 40,
      total: 75,
    },
    lastPlayed: new Date('2023-05-18'),
    achievementsList: [
      {
        id: 1,
        name: "Dragon Slayer",
        description: "Defeat a dragon",
        locked: false,
        unlockDate: new Date('2023-04-19'),
        hidden: false,
        image: "/pictures/achievement_images/skyrim-dragon-slayer.png",
        unlockPercentage: 60,
      },
      {
        id: 2,
        name: "Thieves Guild Master",
        description: "Become the leader of the Thieves Guild",
        locked: false,
        unlockDate: new Date('2023-05-15'),
        hidden: true,
        image: "/pictures/achievement_images/skyrim-thieves-guild-master.png",
        unlockPercentage: 23,
      },
      {
        id: 3,
        name: "Dark Brotherhood Assassin",
        description: "Join the Dark Brotherhood and carry out assassinations",
        locked: true,
        unlockDate: null,
        hidden: false,
        image: "/pictures/achievement_images/skyrim-dark-brotherhood-assassin.png",
        unlockPercentage: 34,
      },
    ],
  },
  {
    id: 7,
    name: "Stardew Valley",
    image: "/pictures/stardew_valley.png",
    achievements: {
      completed: 20,
      total: 40,
    },
    lastPlayed: new Date('2023-05-15'),
    achievementsList: [
      {
        id: 1,
        name: "Green Thumb",
        description: "Grow a certain number of crops",
        locked: false,
        unlockDate: new Date('2023-04-16'),
        hidden: false,
        image: "/pictures/achievement_images/stardew-valley-green-thumb.png",
        unlockPercentage: 44,
      },
      {
        id: 2,
        name: "Master Angler",
        description: "Catch all types of fish",
        locked: false,
        unlockDate: new Date('2023-04-18'),
        hidden: true,
        image: "/pictures/achievement_images/stardew-valley-master-angler.png",
        unlockPercentage: 12,
      },
      {
        id: 3,
        name: "Joja Co. Member of Portal",
        description: "Become a member of Joja Co.",
        locked: true,
        unlockDate: null,
        hidden: false,
        image: "/pictures/achievement_images/stardew-valley-joja-co-member.png",
        unlockPercentage: 44,
      },
    ],
  },
  // Add more game entries with their respective achievements
];